### ISSUE TITLE
Fake no pullup error on too early reset status write

### ISSUE THREAD

**Issue by notaquestion** [adafruit/Adafruit_CircuitPython_seesaw#138]
Using an ATTiny8x7 Breakout and ESP32-S3 Rev TFT Feather (Also tried on a QT PY), 
        
I get this error every hard/button reset and when detaching and re-attaching the breakout:

[2K[0GAuto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2K[0Gcode.py output:
]0;����Wi-Fi: off | code.py | 9.2.0\Traceback (most recent call last):
  File "code.py", line 111, in <module>
  File "/lib/adafruit_seesaw/seesaw.py", line 166, in __init__
  File "/lib/adafruit_seesaw/seesaw.py", line 212, in get_version
  File "/lib/adafruit_seesaw/seesaw.py", line 501, in read
  File "/lib/adafruit_seesaw/seesaw.py", line 520, in write
OSError: [Errno 5] Input/output error
]0;����Wi-Fi: off | 520@/lib/adafruit_seesaw/seesaw.py OSError | 9.2.0\

Followed by this every save/Auto-Reload:  

[2K[0GAuto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2K[0Gcode.py output:
]0;����Wi-Fi: off | code.py | 9.2.0\Traceback (most recent call last):
  File "code.py", line 109, in <module>
RuntimeError: No pull up found on SDA or SCL; check your wiring
]0;����Wi-Fi: off | 109@code.py RuntimeError | 9.2.0\

**Comment by notaquestion** [comment]
I found the same issue here, but closed: https://github.com/adafruit/circuitpython/issues/9535

The bitbangio workout seems to work for me.
