### ISSUE TITLE
Can't import adafruit_seesaw.tftshield18 on RP2040 Raspberry Pi Pico

### ISSUE THREAD

**Issue by rsbohn** [adafruit/Adafruit_CircuitPython_seesaw#57]
Running Adafruit CircuitPython 6.2.0-beta.0 on 2021-01-22; Raspberry Pi Pico with rp2040.

    import board
    from adafruit_seesaw.tftshield18 import TFTShield18

Expected: Should import the module.
Actual: 

    Traceback (most recent call last):
      File "code.py", line 10, in <module>
      File "adafruit_seesaw/tftshield18.py", line 63, in <module>
      File "adafruit_seesaw/tftshield18.py", line 86, in TFTShield18
    AttributeError: 'module' object has no attribute 'I2C'

Fails because of this:

    def __init__(self, i2c_bus=board.I2C(), addr=0x2E):

For the RP2040 Raspberry Pi Pico there is no board.I2C defined.

I've selected GP2=SDA and GP3=SCL on I2C1 and I should be able to create the bus, just need to import TFTShield18 
and pass it my I2C bus instead of using the default.

**Comment by rsbohn** [comment]
'this' is line 69 of https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/master/adafruit_seesaw/tftshield18.py
